/**
 * Roland AIRA Compact S-1 Tweak Synth - Curated Factory Sound & Pattern Presets
 */

const S1_PRESETS = [
  {
    id: 'acid-101',
    name: '01 ACID 101 BASS',
    tempo: 128,
    params: {
      masterVolume: 0.85,
      voiceMode: 'mono',
      portamento: 0.08,
      oscSaw: 0.9,
      oscSquare: 0.5,
      oscPwm: 0.4,
      oscSub: 0.7,
      subMode: 'sub1',
      oscNoise: 0.0,
      oscDrawMix: 0.0,
      oscChop: 0.1,
      oscChopComb: 0.3,
      filterCutoff: 1200,
      filterResonance: 16.0,
      filterHpf: 15,
      filterEnvDepth: 0.75,
      filterKeyFollow: 0.6,
      drive: 0.35,
      envAttack: 0.002,
      envDecay: 0.22,
      envSustain: 0.05,
      envRelease: 0.15,
      lfoRate: 4.5,
      lfoPitchDepth: 0.0,
      lfoFilterDepth: 0.0,
      lfoPwmDepth: 0.3,
      fxChorusSend: 0.15,
      chorusMode: 'type1',
      fxDelaySend: 0.3,
      fxDelayTime: 0.234,
      fxDelayFeedback: 0.35,
      fxReverbSend: 0.2
    },
    pattern: {
      steps: [
        { gate: true, note: 36, velocity: 1.0, probability: 1.0, substep: 1 },
        { gate: true, note: 36, velocity: 0.7, probability: 1.0, substep: 1 },
        { gate: false, note: 36, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 48, velocity: 0.9, probability: 1.0, substep: 2 }, // Flam
        { gate: true, note: 39, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 39, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 41, velocity: 1.0, probability: 1.0, substep: 1 },
        { gate: true, note: 42, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: true, note: 36, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 36, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 48, velocity: 1.0, probability: 1.0, substep: 1 },
        { gate: true, note: 46, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 44, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 44, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 43, velocity: 0.85, probability: 0.75, substep: 2 },
        { gate: true, note: 41, velocity: 0.9, probability: 1.0, substep: 1 }
      ]
    }
  },

  {
    id: 'cyber-chop',
    name: '02 CYBER CHOP LEAD',
    tempo: 130,
    params: {
      masterVolume: 0.8,
      voiceMode: 'poly',
      portamento: 0.02,
      oscSaw: 0.8,
      oscSquare: 0.8,
      oscPwm: 0.7,
      oscSub: 0.2,
      subMode: 'subPulse',
      oscNoise: 0.05,
      oscDrawMix: 0.4,
      oscChop: 0.8,
      oscChopComb: 0.65,
      filterCutoff: 3800,
      filterResonance: 7.0,
      filterHpf: 30,
      filterEnvDepth: 0.45,
      filterKeyFollow: 0.5,
      drive: 0.4,
      envAttack: 0.005,
      envDecay: 0.3,
      envSustain: 0.35,
      envRelease: 0.35,
      lfoRate: 6.0,
      lfoPitchDepth: 0.03,
      lfoFilterDepth: 0.15,
      lfoPwmDepth: 0.5,
      fxChorusSend: 0.4,
      chorusMode: 'type2',
      fxDelaySend: 0.45,
      fxDelayTime: 0.346,
      fxDelayFeedback: 0.45,
      fxReverbSend: 0.35
    },
    pattern: {
      steps: [
        { gate: true, note: 60, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 63, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: true, note: 65, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: true, note: 67, velocity: 1.0, probability: 1.0, substep: 3 }, // Triplet
        { gate: false, note: 67, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 70, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: true, note: 67, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 65, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: true, note: 63, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: false, note: 63, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 60, velocity: 0.95, probability: 1.0, substep: 2 },
        { gate: true, note: 72, velocity: 1.0, probability: 1.0, substep: 1 },
        { gate: false, note: 72, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 70, velocity: 0.85, probability: 0.75, substep: 1 },
        { gate: true, note: 67, velocity: 0.9, probability: 1.0, substep: 1 }
      ]
    }
  },

  {
    id: 'tokyo-chords',
    name: '03 TOKYO NIGHT CHORDS',
    tempo: 118,
    params: {
      masterVolume: 0.8,
      voiceMode: 'chord',
      chordType: 'min7',
      portamento: 0.0,
      oscSaw: 0.85,
      oscSquare: 0.65,
      oscPwm: 0.6,
      oscSub: 0.35,
      subMode: 'sub1',
      oscNoise: 0.02,
      oscDrawMix: 0.2,
      oscChop: 0.0,
      oscChopComb: 0.2,
      filterCutoff: 2200,
      filterResonance: 3.5,
      filterHpf: 20,
      filterEnvDepth: 0.6,
      filterKeyFollow: 0.4,
      drive: 0.15,
      envAttack: 0.01,
      envDecay: 0.45,
      envSustain: 0.3,
      envRelease: 0.5,
      lfoRate: 1.5,
      lfoPitchDepth: 0.01,
      lfoFilterDepth: 0.08,
      lfoPwmDepth: 0.4,
      fxChorusSend: 0.6,
      chorusMode: 'type12',
      fxDelaySend: 0.35,
      fxDelayTime: 0.382,
      fxDelayFeedback: 0.4,
      fxReverbSend: 0.5
    },
    pattern: {
      steps: [
        { gate: true, note: 60, velocity: 0.95, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 63, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 63, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 65, velocity: 0.95, probability: 1.0, substep: 1 },
        { gate: false, note: 65, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 65, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 65, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: true, note: 68, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 68, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 67, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: false, note: 67, velocity: 0.8, probability: 1.0, substep: 1 }
      ]
    }
  },

  {
    id: 'ambient-dream',
    name: '04 AMBIENT DREAM PAD',
    tempo: 90,
    params: {
      masterVolume: 0.8,
      voiceMode: 'poly',
      portamento: 0.05,
      oscSaw: 0.7,
      oscSquare: 0.6,
      oscPwm: 0.75,
      oscSub: 0.4,
      subMode: 'sub2',
      oscNoise: 0.03,
      oscDrawMix: 0.5,
      oscChop: 0.0,
      oscChopComb: 0.2,
      filterCutoff: 1800,
      filterResonance: 2.0,
      filterHpf: 15,
      filterEnvDepth: 0.35,
      filterKeyFollow: 0.5,
      drive: 0.05,
      envAttack: 0.25,
      envDecay: 1.2,
      envSustain: 0.7,
      envRelease: 1.4,
      lfoRate: 0.8,
      lfoPitchDepth: 0.02,
      lfoFilterDepth: 0.12,
      lfoPwmDepth: 0.5,
      fxChorusSend: 0.7,
      chorusMode: 'type2',
      fxDelaySend: 0.5,
      fxDelayTime: 0.5,
      fxDelayFeedback: 0.55,
      fxReverbSend: 0.7
    },
    pattern: {
      steps: [
        { gate: true, note: 60, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 64, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 64, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 64, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 64, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 67, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: false, note: 67, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 67, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 67, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 71, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: false, note: 71, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 71, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: false, note: 71, velocity: 0.8, probability: 1.0, substep: 1 }
      ]
    }
  },

  {
    id: 'unison-supersaw',
    name: '05 UNISON SUPERSAW',
    tempo: 135,
    params: {
      masterVolume: 0.8,
      voiceMode: 'unison',
      portamento: 0.04,
      oscSaw: 1.0,
      oscSquare: 0.8,
      oscPwm: 0.5,
      oscSub: 0.5,
      subMode: 'sub1',
      oscNoise: 0.02,
      oscDrawMix: 0.3,
      oscChop: 0.15,
      oscChopComb: 0.3,
      filterCutoff: 5500,
      filterResonance: 5.0,
      filterHpf: 25,
      filterEnvDepth: 0.5,
      filterKeyFollow: 0.6,
      drive: 0.25,
      envAttack: 0.005,
      envDecay: 0.4,
      envSustain: 0.4,
      envRelease: 0.45,
      lfoRate: 4.0,
      lfoPitchDepth: 0.01,
      lfoFilterDepth: 0.05,
      lfoPwmDepth: 0.4,
      fxChorusSend: 0.5,
      chorusMode: 'type12',
      fxDelaySend: 0.4,
      fxDelayTime: 0.333,
      fxDelayFeedback: 0.45,
      fxReverbSend: 0.4
    },
    pattern: {
      steps: [
        { gate: true, note: 48, velocity: 1.0, probability: 1.0, substep: 1 },
        { gate: true, note: 48, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 60, velocity: 0.9, probability: 1.0, substep: 2 },
        { gate: false, note: 60, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 51, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: true, note: 51, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 58, velocity: 0.95, probability: 1.0, substep: 1 },
        { gate: true, note: 55, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: true, note: 46, velocity: 1.0, probability: 1.0, substep: 1 },
        { gate: false, note: 46, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 58, velocity: 0.9, probability: 1.0, substep: 1 },
        { gate: true, note: 56, velocity: 0.85, probability: 1.0, substep: 1 },
        { gate: true, note: 55, velocity: 0.9, probability: 1.0, substep: 2 },
        { gate: true, note: 53, velocity: 0.8, probability: 1.0, substep: 1 },
        { gate: true, note: 51, velocity: 0.85, probability: 0.75, substep: 4 }, // Quad ratchet
        { gate: true, note: 50, velocity: 0.9, probability: 1.0, substep: 1 }
      ]
    }
  }
];

window.S1_PRESETS = S1_PRESETS;
